In [2]:
import numpy as np

In [3]:
x=np.zeros((3,4))

In [4]:
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
x = np.ones((2,3,4),dtype='int16')

In [11]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
x=np.arange(10,25,5)

In [13]:
x

array([10, 15, 20])

In [14]:
x = np.linspace(0,2,9)

In [15]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
x = np.full ((2,2),7)

In [17]:
x

array([[7, 7],
       [7, 7]])

In [18]:
x=np.eye(2)

In [19]:
x

array([[1., 0.],
       [0., 1.]])

In [20]:
x=np.random.random((2,2))

In [21]:
x

array([[0.80032295, 0.89361178],
       [0.39113708, 0.3142747 ]])

In [22]:
x=np.empty((3,2))


In [23]:
x 

array([[9.34577196e-307, 9.34598246e-307],
       [1.60218491e-306, 1.69119873e-306],
       [1.24611673e-306, 1.00136897e-307]])

In [28]:
x = np.array([[2,4,6],[8,5,6]])

In [29]:
x

array([[2, 4, 6],
       [8, 5, 6]])

In [30]:
i = np.transpose(x)

In [31]:
i

array([[2, 8],
       [4, 5],
       [6, 6]])

In [32]:
a= np.array([1,3,4])


In [33]:
b=np.array([2,3,5])

In [34]:
np.add(b,a)


array([3, 6, 9])